### ISSUE TITLE
Galactic Support

### ISSUE THREAD

**Issue by maspe36** [ros2/rosidl_typesupport_connext#70]
After lots of digging, I believe I need this package to use the existing RTI .idl files from my native DDS application to generate an interface package for ROS2. Unfortunately I'm on galactic and it seems like foxy is the latest released version of this package. 

Instructions on building this locally inplace of a distro release would also be super helpful

**Comment by clalancette** [comment]
We've switched to using https://github.com/ros2/rmw_connextdds in Galactic and newer.  I'll suggest that you look there for information about integrating your native DDS application.
